Repository mongodb/docs-node, pull requests merged in 2025-02, with the labels that each got.

#959 DOCSP-46712 ListIndexesOptions 404
  source/fundamentals/indexes.txt
Labels: backport v6.10, backport v6.9, backport v6.8, backport v6.7, backport v6.6, backport v6.11, backport v6.12, backport v6.13

#960 DOCSP-46711 MongoClientOptions 404
  source/fundamentals/connection/network-compression.txt
Labels: backport v6.10, backport v6.9, backport v6.8, backport v6.7, backport v6.6, backport v6.5, backport v6.4, backport v6.3, backport v6.2, backport v6.1, backport v6.0, backport v6.11, backport v6.12, backport v6.13

#979 DOCSP-46884 Abort signal support
  source/code-snippets/crud/cursor.js
  source/fundamentals/crud/read-operations/cursor.txt
Labels: backport v6.13

#981 DOCSP-46811 Standardized Logger
  source/fundamentals/logging.txt
  source/includes/fundamentals/logging.js
  source/whats-new.txt
Labels: backport v6.13
